### ISSUE TITLE
Create New Post Page

### ISSUE THREAD

**Issue by Superior126** [Superior126/easy-newsroom#2]
Add a page where site admins can post new news updates.

**Tasks**

- [x] Create New Post Page
- [x] Add UI elements for site owners to interact with.
- [ ] Add functionality to UI page.

**Comment by Superior126** [comment]
# Added UI Elements
This is the skeleton of the page. No Functionality yet.
![image](https://github.com/Superior126/easy-newsroom/assets/90008321/09e975d2-0630-4278-b9ff-3b91dd175834)
